runtime: python27
threadsafe: true

builtins:
- remote_api: on
env_variables:
  ALLOWED_HOSTS: "*"
handlers:
- url: /_ah/(mapreduce|queue|warmup).*
  script: pokedex.wsgi.application
  login: admin
- url: /static
  static_dir: static/
- url: /.*
  script: pokedex.wsgi.application
libraries:
- name: django
  version: "1.11"
