# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0003_species_elements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.IntegerField()),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='elements.Element')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='elements.Element')),
            ],
        ),
    ]
