# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0002_importelements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('pokedex', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('types', models.ManyToManyField(to='elements.Element')),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
    ]
