# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 11:26
from __future__ import unicode_literals

import csv
from django.db import migrations

def ImportSpecies(apps, schema_editor):
    Species = apps.get_model('species', 'Species')
    with open('veekun/pokedex/data/csv/pokemon_species.csv', 'r') as species_f:
        data = csv.DictReader(species_f.read().splitlines())
    for row in data:
        if row['generation_id'] == '1':
            Species.objects.create(
                pokedex=row['id'],
                identifier=row['identifier'],
            )

class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ImportSpecies),
    ]
