# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 11:55
from __future__ import unicode_literals

import djangae.fields.related
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_importelements'),
        ('species', '0002_importspecies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='types',
        ),
        migrations.AddField(
            model_name='species',
            name='types',
            field=djangae.fields.related.RelatedSetField(to='elements.Element'),
        ),
    ]
