# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-19 14:50
from __future__ import unicode_literals

from django.db import migrations

def CreateMeltan(apps, schema_editor):
    Species = apps.get_model('species', 'Species')
    Element = apps.get_model('elements', 'Element')
    steel = Element.objects.get(identifier='steel')
    for pkmn in [(808,'meltan'),(809,'melmetal')]:
        s = Species.objects.create(
            pokedex=pkmn[0],
            identifier=pkmn[1],
        )
        s.types.add(steel)

class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_importelements'),
        ('species', '0002_importspecies'),
    ]

    operations = [
        migrations.RunPython(CreateMeltan),
    ]
